title: Vlad Ciobancai Site
description: My minimal GitHub Pages site

# Use the Linux console theme
remote_theme: b2a3e8/jekyll-theme-console
style: dark   # or: hacker, light, nord

plugins:
  - jekyll-remote-theme

markdown: kramdown
