title: Vlad Ciobancai Terminal Site
description: My GitHub Pages site with a console-like theme

remote_theme: b2a3e8/jekyll-theme-console
style: dark              # or light, hacker, nord
listen_for_clients_preferred_style: true  # optional: auto-switch based on user OS preference

plugins:
  - jekyll-remote-theme

markdown: kramdown

# Optional console theme config:
header_pages:
  - index.md
footer: "Built by Vlad"
disable_google_fonts: false  # or true, if you want no external font loading
